services:
  - type: web
    name: catcollector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn catcollector.wsgi:application
